# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Run Jekyll on Windows'
url:              http://aiskakov.github.io/run-jekyll-on-windows/
baseurl:          /

github:
  repo:           https://github.com/aiskakov/run-jekyll-on-windows

author:
  name:           'Julian Thilo'
  url:            https://twitter.com/juthilo
